# Generated by Django 5.2.4 on 2025-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='bio',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF recommended)', null=True, upload_to='bio/resume/'),
        ),
    ]
