# Generated by Django 5.2.4 on 2025-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_bio_resume_url_bio_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='social_links',
        ),
        migrations.AddField(
            model_name='bio',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL', null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='twitch_url',
            field=models.URLField(blank=True, help_text='Twitch channel URL', null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='x_url',
            field=models.URLField(blank=True, help_text='X.com (Twitter) profile URL', null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True),
        ),
    ]
